export const LOGIN="LOGIN"
export const LOGIN_FAILED="LOGIN_FAILED"
<<<<<<< HEAD
export const ADD_LANDMARK="ADD_LANDMARK"
export const ADD_LANDMARK_FAILED="ADD_LANDMARK_FAILED"
export const LOGOUT="LOGOUT"
=======

export const LOGOUT="LOGOUT"
export const PORTFOLIO_LIST="PORTFOLIO_LIST"

export const ADD_LANDMARK="ADD_LANDMARK"
export const ADD_LANDMARK_FAILED="ADD_LANDMARK_FAILED"

>>>>>>> 677a862d818ccb8d5bd9fdc4bae7b3b76078ba4f
