export const LOGIN="LOGIN"
export const LOGIN_FAILED="LOGIN_FAILED"
export const LOGOUT="LOGOUT"

export const ADD_LANDMARK="ADD_LANDMARK"
export const ADD_LANDMARK_FAILED="ADD_LANDMARK_FAILED"
export const LANDMARK_LIST="LANDMARK_LIST"

export const ADD_PORTFOLIO="ADD_PORTFOLIO"
export const ADD_PORTFOLIO_FAILED="ADD_PORTFOLIO_FAILED"
export const PORTFOLIO_LIST="PORTFOLIO_LIST"